### ISSUE TITLE
Refactor serializers with Blueprinter

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#206]
https://github.com/procore/blueprinter

**Comment by guieiras** [comment]
I can do it! Would like to open an Pull request for this.

**Comment by dreikanter** [comment]
@guieiras Cool! Please, go ahead.

I'll better add some comments here. This refactoring suppose to:

- Replace all `serializers/*_serializer.rb` with Blueprinter classes
- Merge `BriefFeedSerializer` with `FeedSerializer` into a single "blueprint" (could be done with a Blueprinter view for brief mode)
- Update `S11nHelpers` and related calls
- Drop irrelevant dependencies from `Gemfile` if there are any
- Ensure new classes are covered with tests
