### ISSUE TITLE
Replace PostStatus.ignored with PostStatus.non_valid

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#248]
To improve terminology.

**Comment by IMPrimph** [comment]
@dreikanter 
Where exactly is that
I can't find

**Comment by dreikanter** [comment]
@IMPrimph Here are couple of references: https://github.com/dreikanter/feeder/search?q=ignored

It will be necessary to check if the old `ignored` records are treated as `non_valid` after the rename. I don't remember if Rails enum will handle this transition transparently.

**Comment by dreikanter** [comment]
#319
