### ISSUE TITLE
Replace Vagrant VM with Docker Compose configuration

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/feeder#250]
Docker Compose configuration should include:

- Rails server
- PostgreSQL
- Webpack dev server

**Comment by ThirumlaDevi** [comment]
@dreikanter I was able to set up the local environment without using the Vagrant VM for the feeder service, correct me if i'm wrong regarding the requirements of this issue. 
For the dev environment, you need a docker setup for the rails app (which will render the feeds service)+ PostgreSQL db ( rails app will communicate with the postgresql) + Webpack dev server ( to bundle the frontend related files and serve it to the rails app when rendered in the browser)
However, i am unable to understand where the other 2 services specified in the issue description (Redis & Sidekiq), play a role in this setup. 
Can you please let me know if i have gotten the requirements right?

**Comment by dreikanter** [comment]
@ThirumlaDevi Hello! At this stage feeder doesn't use Sidekiq/Redis. It will be enough to have only the essential services that you listed. Also Headless Chrome is not needed. I'll update the issue description.

Thank you for your help!

**Comment by ThirumlaDevi** [comment]
@dreikanter Great! I would like to pick this issue, i think i can make a neat docker setup for your project now that I am clear on the architecture of the project, Can you please assign this task to me ?

**Comment by ThirumlaDevi** [comment]
@dreikanter For now i am manually configuring the database.yml with postgres user name, password and database name, to work with my setup. I tried the below configuration to set _database_url_ as a ENV, but it seems to not do the needful. 
```
export POSTGRES_HOST=postgres
export POSTGRES_PORT=5432
export POSTGRES_DB=marketing
export POSTGRES_USER=username
export POSTGRES_PASSWORD=password
export DATABASE_URL=postgres://username:password@localhost:5432/marketing
```
Can you please include details on how to configure **_database_url_**  for postgresql adapter to accept? TIA

**Comment by dreikanter** [comment]
@ThirumlaDevi At the moment I'm using encrypted Rails credentials to set DB URL for all environments. It is not necessary to have these values encrypted for dev and test environment, since it is not a secret.

I would expect `url` values here to be replaced with something like `ENV.fetch('DATABASE_URL')` to work with env variables-based Docker configuration:

https://github.com/dreikanter/feeder/blob/9c8a1413cdc8eb8287ee92f5aebef7b7596d6fb7/config/database.yml#L1-L7

Also, when you set `DATABASE_URL` variable there is no need in others (`POSTGRES_HOST`, etc) since the URL suppose to include everything anyway.

Current DB URL value is `postgres://postgres:postgres@localhost/feeder_development`. You may see the way I'm configuring Postgres on Vagrant VM here: https://github.com/dreikanter/feeder/blob/master/provision.sh

**Comment by ThirumlaDevi** [comment]
@dreikanter 
I am happy to inform you that I am done with the docker setup. 
I have one doubt, when i checked the [contribution](https://github.com/dreikanter/feeder#contribution) page it says that we need to develop over the dev branch. But, there are close to 183 file changes between dev(base) and master(comparer), according to [git compare](https://github.com/dreikanter/feeder/compare/dev...master)
Feeder project's master branch code's ruby version requirement is 2.6.5 and that of dev branch is 2.7. 
The decision to which branch that i need to give this PR to will directly affect the Dockerfile changes. Can you please let me know to which branch i need to give the PR to? TIA

**Comment by dreikanter** [comment]
@ThirumlaDevi Contributions document is obsolete, thank you for noticing this. Please make the PR to master branch. I'll update Ruby later.

**Comment by ThirumlaDevi** [comment]
@dreikanter I have raised [PR-263](https://github.com/dreikanter/feeder/pull/263) for the docker setup.
But, there seems to be some failures while running the job  "Run linter and test suite / test (pull_request)" after raising the PR. 
It seems like the job is trying to **load database configuration**, but i have changed the database configuration to get **database url for environment variable** when in **development**, as per [this suggestion](https://github.com/dreikanter/feeder/issues/250#issuecomment-706540103).
Please do correct me if i am wrong.

**Comment by dreikanter** [comment]
@ThirumlaDevi DB configuration fails because GitHub Actions don't have the new `DATABASE_URL` env variable defined. And even if I add it to the project "secrets", it won't be propagated to the tests running on the forked repo.

The solution could be updating GitHub Actions configuration to use the new Docker configuration that includes `DATABASE_URL` for the test and dev environments. But this is outside from the scope of the current issue. It's ok if the test suite runs locally.

**Comment by dreikanter** [comment]
#263 is accepted 🎉
