### ISSUE TITLE
Import ещёнепознер

### ISSUE THREAD

**Issue by fetsh** [dreikanter/feeder#84]
https://www.youtube.com/channel/UCNRYbltJXhf6DepS26-uSbQ

**Comment by dreikanter** [comment]
https://candy.freefeed.net/nepozner
https://freefeed.net/nepozner

Channel ID: UCNRYbltJXhf6DepS26-uSbQ

@nepozner - Ещё непознер. Еженедельные беседы с интересными героями. - https://www.youtube.com/channel/UCNRYbltJXhf6DepS26-uSbQ
