### ISSUE TITLE
Saturday Morning Breakfast Cereal

### ISSUE THREAD

**Issue by glukki** [dreikanter/feeder#93]
Could you add this comics source, please? :3
https://www.smbc-comics.com

**Comment by dreikanter** [comment]
Absolutely :)

**Comment by glukki** [comment]
They say, there're important additions in these comics:
- a hover message;
- an image behind the red button.

![screenshot 2019-01-13 at 23 25 54](https://user-images.githubusercontent.com/140462/51090334-74dc5300-178b-11e9-98a0-4b8b144d2c24.png)

**Comment by dreikanter** [comment]
https://freefeed.net/smbc
https://candy.freefeed.net/smbc

**Comment by dreikanter** [comment]
parsed_description = Nokogiri::HTML(entity.description)
parsed_description.css('p').first.children.text
parsed_description.css('img').first.attributes['src'].value

**Comment by dreikanter** [comment]
Red button: 

content = Nokogiri::HTML(RestClient.get(link).body)
content.css('#aftercomic img').first.attributes['src'].value
